"""password added and changes made to models 2

Revision ID: 0f692829bdbd
Revises: 2c1c3fb8a1f0
Create Date: 2025-07-22 21:39:33.089544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f692829bdbd'
down_revision = '2c1c3fb8a1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_status_reports_changed_by_users'), type_='foreignkey')
        batch_op.drop_column('changed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed_by', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_status_reports_changed_by_users'), 'users', ['changed_by'], ['id'])

    # ### end Alembic commands ###
