"""uuser model updated again

Revision ID: 2c1c3fb8a1f0
Revises: 5578f2818d4b
Create Date: 2025-07-22 20:25:36.971942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1c3fb8a1f0'
down_revision = '5578f2818d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_contacts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_contacts'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_locations_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('media_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_media_attachments_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_attachments'))
    )
    op.create_table('status_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_status_reports_changed_by_users')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_status_reports_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('status')
        batch_op.drop_column('longitude')
        batch_op.drop_column('image')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=False))

    op.drop_table('status_reports')
    op.drop_table('media_attachments')
    op.drop_table('locations')
    op.drop_table('emergency_contacts')
    # ### end Alembic commands ###
