"""co user.py added

Revision ID: 5578f2818d4b
Revises: 4cb9a7ca22e3
Create Date: 2025-07-19 00:00:11.961312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5578f2818d4b'
down_revision = '4cb9a7ca22e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
